# Generated by Django 4.1 on 2022-09-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_two_wheeler_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='two_wheeler',
            old_name='Bike_title',
            new_name='title',
        ),
    ]
