# Generated by Django 4.1 on 2022-09-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_four_wheeler_url_two_wheeler_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='four_wheeler',
            old_name='url',
            new_name='carurl',
        ),
        migrations.RenameField(
            model_name='two_wheeler',
            old_name='url',
            new_name='bikeurl',
        ),
    ]
