# Generated by Django 4.1 on 2022-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_four_wheeler_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100)),
                ('staffAddress', models.CharField(max_length=100)),
                ('staffpancard', models.CharField(max_length=100)),
                ('staffaadharcardno', models.CharField(max_length=100)),
                ('staffphoneno', models.CharField(max_length=100)),
            ],
        ),
    ]
