# Generated by Django 4.1 on 2022-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
